# Generated by Django 4.1.7 on 2023-03-18 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2)])),
                ('surname', models.CharField(blank=True, max_length=35, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('feedback', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/feedback')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
