# Generated by Django 4.1.7 on 2023-03-19 07:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markmodel',
            options={'verbose_name': 'Марка телефона', 'verbose_name_plural': 'Марки телефонов'},
        ),
        migrations.AlterModelOptions(
            name='phonemodel',
            options={'ordering': ['-price_p', 'mark_p', '-model_p'], 'verbose_name': 'Модель телефона', 'verbose_name_plural': 'Модели телефонов'},
        ),
        migrations.AddField(
            model_name='phonemodel',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Публикация'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='discount_p',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='mark_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop_app.markmodel', verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='model_p',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='photo',
            field=models.ImageField(upload_to='photos/phones', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='price_p',
            field=models.PositiveIntegerField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='slug',
            field=models.SlugField(default='', verbose_name='Ссылка'),
        ),
    ]
