# Generated by Django 4.1.7 on 2023-03-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_markmodel_slug_alter_markmodel_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonemodel',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
